### ISSUE TITLE
[task] Trace storage model and ITraceStorage interface definition

### ISSUE THREAD

**Issue by liuhaoyang** [dotnetcore/mocha#7]
1. Determine the storage model for trace data 
2. Ability to efficiently query corresponding span data using trace IDs 
3. Ability to filter and query trace lists using service name, operation, or tags, as shown below
![image](https://github.com/dotnetcore/mocha/assets/10701915/8e83728c-060e-4369-a0bd-3a151bd724cc)

**Comment by KawhiWei** [comment]
@liuhaoyang What is  OperationName？

**Comment by liuhaoyang** [comment]
> @liuhaoyang What is OperationName？

`OperationName` is another name for `Span Name`.

**Comment by KawhiWei** [comment]
> > 什么是操作名称？
> 
> `OperationName`是 的另一个名称。`Span Name`

OK
